# prettier-ignore
specVersion: 1.3.0
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: UrdFactory
    network: {{network}}
    source:
      address: "{{UrdFactoryAddress}}"
      abi: UrdFactory
      startBlock: {{UrdFactoryStartBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.9
      language: wasm/assemblyscript
      entities:
        - UrdCreated
      abis:
        - name: UrdFactory
          file: ./abis/UrdFactory.json
        - name: UniversalRewardsDistributor
          file: ./abis/UniversalRewardsDistributor.json
      eventHandlers:
        - event: UrdCreated(indexed address,indexed address,indexed
            address,uint256,bytes32,bytes32,bytes32)
          handler: handleUrdCreated
      file: ./src/urd-factory.ts
templates:
  - kind: ethereum
    name: UniversalRewardsDistributor
    network: {{network}}
    source:
      abi: UniversalRewardsDistributor
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.9
      language: wasm/assemblyscript
      entities:
        - Claimed
        - OwnerSet
        - PendingRootRevoked
        - PendingRootSet
        - RootSet
        - RootUpdaterSet
        - TimelockSet
      abis:
        - name: UniversalRewardsDistributor
          file: ./abis/UniversalRewardsDistributor.json
      eventHandlers:
        - event: Claimed(indexed address,indexed address,uint256)
          handler: handleClaimed
        - event: OwnerSet(indexed address)
          handler: handleOwnerSet
        - event: PendingRootRevoked(indexed address)
          handler: handlePendingRootRevoked
        - event: PendingRootSet(indexed address,indexed bytes32,indexed bytes32)
          handler: handlePendingRootSet
        - event: RootSet(indexed bytes32,indexed bytes32)
          handler: handleRootSet
        - event: RootUpdaterSet(indexed address,bool)
          handler: handleRootUpdaterSet
        - event: TimelockSet(uint256)
          handler: handleTimelockSet
      file: ./src/universal-rewards-distributor.ts
