# prettier-ignore
apiVersion: 3
name: royco-rwa-markets-pipeline
resource_size: s
sources:
  royco_rwa_market_state_reference:
    name: market_state
    subgraphs:
      {{#metadata}}
      - name: royco-rwa-markets-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
  royco_rwa_vault_state_reference:
    name: vault_state
    subgraphs:
      {{#metadata}}
      - name: royco-rwa-markets-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
  royco_rwa_global_token_transfer_reference:
    name: global_token_transfer
    subgraphs:
      {{#metadata}}
      - name: royco-rwa-markets-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
  royco_rwa_global_token_activity_reference:
    name: global_token_activity
    subgraphs:
      {{#metadata}}
      - name: royco-rwa-markets-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
  royco_rwa_position_state_reference:
    name: position_state
    subgraphs:
      {{#metadata}}
      - name: royco-rwa-markets-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
  royco_rwa_position_latest_reference:
    name: position_latest
    subgraphs:
      {{#metadata}}
      - name: royco-rwa-markets-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
  royco_rwa_position_historical_reference:
    name: position_historical
    subgraphs:
      {{#metadata}}
      - name: royco-rwa-markets-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
  royco_rwa_position_historical_hourly_reference:
    name: position_historical_hourly
    subgraphs:
      {{#metadata}}
      - name: royco-rwa-markets-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
  royco_rwa_position_historical_daily_reference:
    name: position_historical_daily
    subgraphs:
      {{#metadata}}
      - name: royco-rwa-markets-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
  royco_rwa_metric_latest_reference:
    name: metric_latest
    subgraphs:
      {{#metadata}}
      - name: royco-rwa-markets-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
  royco_rwa_metric_historical_reference:
    name: metric_historical
    subgraphs:
      {{#metadata}}
      - name: royco-rwa-markets-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
  royco_rwa_metric_historical_hourly_reference:
    name: metric_historical_hourly
    subgraphs:
      {{#metadata}}
      - name: royco-rwa-markets-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
  royco_rwa_metric_historical_daily_reference:
    name: metric_historical_daily
    subgraphs:
      {{#metadata}}
      - name: royco-rwa-markets-{{network}}
        version: {{version}}
      {{/metadata}}
    type: subgraph_entity
transforms: {}
sinks:
  royco_rwa_market_state_postgres:
    type: postgres
    table: market_state
    schema: public
    secret_name: NEON_ROYCO_ESTATE
    description: "Postgres sink for: market_state"
    from: royco_rwa_market_state_reference
  royco_rwa_vault_state_postgres:
    type: postgres
    table: vault_state
    schema: public
    secret_name: NEON_ROYCO_ESTATE
    description: "Postgres sink for: vault_state"
    from: royco_rwa_vault_state_reference
  royco_rwa_global_token_transfer_postgres:
    type: postgres
    table: global_token_transfer
    schema: public
    secret_name: NEON_ROYCO_ESTATE
    description: "Postgres sink for: global_token_transfer"
    from: royco_rwa_global_token_transfer_reference
  royco_rwa_global_token_activity_postgres:
    type: postgres
    table: global_token_activity
    schema: public
    secret_name: NEON_ROYCO_ESTATE
    description: "Postgres sink for: global_token_activity"
    from: royco_rwa_global_token_activity_reference
  royco_rwa_position_state_postgres:
    type: postgres
    table: position_state
    schema: public
    secret_name: NEON_ROYCO_ESTATE
    description: "Postgres sink for: position_state"
    from: royco_rwa_position_state_reference
  royco_rwa_position_latest_postgres:
    type: postgres
    table: position_latest
    schema: public
    secret_name: NEON_ROYCO_ESTATE
    description: "Postgres sink for: position_latest"
    from: royco_rwa_position_latest_reference
  royco_rwa_position_historical_postgres:
    type: postgres
    table: position_historical
    schema: public
    secret_name: NEON_ROYCO_ESTATE
    description: "Postgres sink for: position_historical"
    from: royco_rwa_position_historical_reference
  royco_rwa_position_historical_hourly_postgres:
    type: postgres
    table: position_historical_hourly
    schema: public
    secret_name: NEON_ROYCO_ESTATE
    description: "Postgres sink for: position_historical_hourly"
    from: royco_rwa_position_historical_hourly_reference
  royco_rwa_position_historical_daily_postgres:
    type: postgres
    table: position_historical_daily
    schema: public
    secret_name: NEON_ROYCO_ESTATE
    description: "Postgres sink for: position_historical_daily"
    from: royco_rwa_position_historical_daily_reference
  royco_rwa_metric_latest_postgres:
    type: postgres
    table: metric_latest
    schema: public
    secret_name: NEON_ROYCO_ESTATE
    description: "Postgres sink for: metric_latest"
    from: royco_rwa_metric_latest_reference
  royco_rwa_metric_historical_postgres:
    type: postgres
    table: metric_historical
    schema: public
    secret_name: NEON_ROYCO_ESTATE
    description: "Postgres sink for: metric_historical"
    from: royco_rwa_metric_historical_reference
  royco_rwa_metric_historical_hourly_postgres:
    type: postgres
    table: metric_historical_hourly
    schema: public
    secret_name: NEON_ROYCO_ESTATE
    description: "Postgres sink for: metric_historical_hourly"
    from: royco_rwa_metric_historical_hourly_reference
  royco_rwa_metric_historical_daily_postgres:
    type: postgres
    table: metric_historical_daily
    schema: public
    secret_name: NEON_ROYCO_ESTATE
    description: "Postgres sink for: metric_historical_daily"
    from: royco_rwa_metric_historical_daily_reference