# prettier-ignore
specVersion: 1.3.0
schema:
  file: ./schema.graphql
dataSources:
{{#asyncVaults}}
  - kind: ethereum
    name: Vault{{id}}
    network: {{network}}
    source:
      address: "{{vaultAddress}}"
      abi: AsyncVaultConcrete
      startBlock: {{startBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.9
      language: wasm/assemblyscript
      entities:
        - Transfer
        - Deposit
        - Withdraw
        - QueuedWithdrawal
        - RequestCancelled
        - RequestMovedToNextEpoch
        - EpochClosed
        - EpochProcessed
        - RequestClaimed
      abis:
        - name: BaseVault
          file: ./abis/BaseVault.json
        - name: AsyncVaultConcrete
          file: ./abis/AsyncVaultConcrete.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
        - event: Deposit(indexed address,indexed address,uint256,uint256)
          handler: handleDeposit
        - event: Withdraw(indexed address,indexed address,indexed address,uint256,uint256)
          handler: handleWithdraw
        - event: QueuedWithdrawal(indexed address,indexed address,indexed address,uint256,uint256,uint256)
          handler: handleQueuedWithdrawal
        - event: RequestCancelled(indexed address,uint256,uint256)
          handler: handleRequestCancelled
        - event: RequestMovedToNextEpoch(indexed address,uint256,uint256,uint256)
          handler: handleRequestMovedToNextEpoch
        - event: EpochClosed(uint256)
          handler: handleEpochClosed
        - event: EpochProcessed(uint256,uint256,uint256,uint256)
          handler: handleEpochProcessed
        - event: RequestClaimed(indexed address,uint256,uint256[])
          handler: handleRequestClaimed
      file: ./src/async-vault-concrete.ts
{{/asyncVaults}}
{{#standardVaults}}
  - kind: ethereum
    name: Vault{{id}}
    network: {{network}}
    source:
      address: "{{vaultAddress}}"
      abi: BaseVault
      startBlock: {{startBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.9
      language: wasm/assemblyscript
      entities:
        - Transfer
        - Deposit
        - Withdraw
      abis:
        - name: BaseVault
          file: ./abis/BaseVault.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
        - event: Deposit(indexed address,indexed address,uint256,uint256)
          handler: handleDeposit
        - event: Withdraw(indexed address,indexed address,indexed address,uint256,uint256)
          handler: handleWithdraw
      file: ./src/vault.ts
{{/standardVaults}}
